CREATE SEQUENCE IF NOT EXISTS SEQ_FLIGHT_LEG
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  CACHE 1;

CREATE TABLE IF NOT EXISTS FLIGHT (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_FLIGHT_LEG'),
    FLIGHT_ID VARCHAR(64) NOT NULL,
    CARRIER_CODE VARCHAR(8) NOT NULL,
    FLIGHT_NUMBER BIGINT NOT NULL,
    FLIGHT_DATE DATE NOT NULL,
    TRAFFIC VARCHAR(16) NOT NULL,
    DEPARTURE_AIRPORT VARCHAR(8) NOT NULL,
    ARRIVAL_AIRPORT VARCHAR(8) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
    );

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_FLIGHT_FLIGHT_ID ON FLIGHT (FLIGHT_ID);

CREATE SEQUENCE IF NOT EXISTS REVINFO_SEQ
  INCREMENT BY 50
  START WITH 1
  MINVALUE 1
  CACHE 1;

CREATE TABLE IF NOT EXISTS REVINFO (
    REV INT PRIMARY KEY,
    REVTSTMP BIGINT
);

CREATE TABLE IF NOT EXISTS FLIGHT_AUD (
    ID BIGINT NOT NULL,
    REV INT NOT NULL,
    REVTYPE SMALLINT,
    FLIGHT_ID VARCHAR(64) NOT NULL,
    CARRIER_CODE VARCHAR(8) NOT NULL,
    FLIGHT_NUMBER BIGINT NOT NULL,
    FLIGHT_DATE DATE NOT NULL,
    TRAFFIC VARCHAR(16) NOT NULL,
    DEPARTURE_AIRPORT VARCHAR(8) NOT NULL,
    ARRIVAL_AIRPORT VARCHAR(8) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID, REV)
    );

ALTER TABLE FLIGHT_AUD
    ADD CONSTRAINT FK_FLIGHT_AUD_REV
        FOREIGN KEY (REV) REFERENCES REVINFO (REV);