CREATE SEQUENCE IF NOT EXISTS SEQ_FLIGHT_LEG
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  CACHE 1;

CREATE TABLE IF NOT EXISTS FLIGHT (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_FLIGHT_LEG'),
    FLIGHT_ID VARCHAR(64),
    CARRIER_CODE VARCHAR(8),
    FLIGHT_NUMBER BIGINT,
    FLIGHT_DATE DATE,
    TRAFFIC VARCHAR(16),
    DEPARTURE_AIRPORT VARCHAR(8),
    ARRIVAL_AIRPORT VARCHAR(8),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
    );

CREATE INDEX IF NOT EXISTS IDX_FLIGHT_FLIGHT_ID ON FLIGHT (FLIGHT_ID);

CREATE TABLE IF NOT EXISTS REVINFO (
                                       REV INTEGER PRIMARY KEY,
                                       REVTSTMP BIGINT
);

CREATE SEQUENCE IF NOT EXISTS REVINFO_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE REVINFO
    ALTER COLUMN REV SET DEFAULT NEXTVAL('REVINFO_SEQ');

CREATE TABLE IF NOT EXISTS FLIGHT_AUD (
    ID BIGINT NOT NULL,
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    FLIGHT_ID VARCHAR(64),
    CARRIER_CODE VARCHAR(8),
    FLIGHT_NUMBER BIGINT,
    FLIGHT_DATE DATE,
    TRAFFIC VARCHAR(16),
    DEPARTURE_AIRPORT VARCHAR(8),
    ARRIVAL_AIRPORT VARCHAR(8),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_FLIGHT_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO (REV)
    );

CREATE INDEX IF NOT EXISTS IDX_FLIGHT_AUD_REV ON FLIGHT_AUD (REV);