CREATE SEQUENCE IF NOT EXISTS SEQ_FLIGHT_LEG
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  CACHE 1;

CREATE TABLE IF NOT EXISTS FLIGHT (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_FLIGHT_LEG'),
    FLIGHT_ID VARCHAR(64),
    CARRIER_CODE VARCHAR(8),
    FLIGHT_NUMBER BIGINT,
    FLIGHT_DATE DATE,
    TRAFFIC VARCHAR(16),
    DEPARTURE_AIRPORT VARCHAR(8),
    ARRIVAL_AIRPORT VARCHAR(8),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
    );

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_FLIGHT_FLIGHT_ID ON FLIGHT (FLIGHT_ID);